apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory
        image: 866934333672.dkr.ecr.us-east-2.amazonaws.com/vehicle-inventory-image:0.0.1
        ports:
        - containerPort: 8081
