apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-service
  template:
    metadata:
      labels:
        app: spring-service
    spec:
      containers:
      - name: inventory
        image: 866934333672.dkr.ecr.us-east-2.amazonaws.com/vehicle-inventory-image:0.0.1
        ports:
        - containerPort: 8081
