#Imperative command to create service to expose frontend deployment 
#kubectl expose deploy api \ --name=api \ --type=LoadBalancer \ --port=80 \ --target-port=8080
apiVersion: v1
kind: Service
metadata:
  name: spring
  labels:
    app: spring
spec:
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
