apiVersion: apps/v1
kind: Deployment
metadata:
  name: vservice-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vservice-app
  template:
    metadata:
      labels:
        app: vservice-app
    spec:
      containers:
      - name: vservice
        image:  866934333672.dkr.ecr.us-east-2.amazonaws.com/vehicle-service-image:0.0.1
        ports:
        - containerPort: 8083
